
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menudepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItemListing   
  template:
    metadata:
      labels:
        app: MenuItemListing
    spec:
      containers:
      - name: menuitemlisting
        image: first1cr.azurecr.io/menuitemlistingrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: firstapisn

---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlisting
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItemListing